# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_toporobotimporter.ui'
#
# Created: Sat Feb 15 20:25:37 2014
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ToporobotImporter(object):
    def setupUi(self, ToporobotImporter):
        ToporobotImporter.setObjectName(_fromUtf8("ToporobotImporter"))
        ToporobotImporter.resize(585, 547)
        self.buttonBox = QtGui.QDialogButtonBox(ToporobotImporter)
        self.buttonBox.setGeometry(QtCore.QRect(10, 510, 561, 31))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Help|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gbInput = QtGui.QGroupBox(ToporobotImporter)
        self.gbInput.setGeometry(QtCore.QRect(10, 0, 561, 180))
        self.gbInput.setObjectName(_fromUtf8("gbInput"))
        self.verticalLayout = QtGui.QVBoxLayout(self.gbInput)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.gbInput)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(150, 0))
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.leToporobotText = QgsFileDropEdit(self.gbInput)
        self.leToporobotText.setObjectName(_fromUtf8("leToporobotText"))
        self.horizontalLayout.addWidget(self.leToporobotText)
        self.bBrowseToporobotText = QtGui.QToolButton(self.gbInput)
        self.bBrowseToporobotText.setObjectName(_fromUtf8("bBrowseToporobotText"))
        self.horizontalLayout.addWidget(self.bBrowseToporobotText)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(self.gbInput)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(150, 0))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.leToporobotCoord = QgsFileDropEdit(self.gbInput)
        self.leToporobotCoord.setObjectName(_fromUtf8("leToporobotCoord"))
        self.horizontalLayout_2.addWidget(self.leToporobotCoord)
        self.bBrowseToporobotCoord = QtGui.QToolButton(self.gbInput)
        self.bBrowseToporobotCoord.setObjectName(_fromUtf8("bBrowseToporobotCoord"))
        self.horizontalLayout_2.addWidget(self.bBrowseToporobotCoord)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_4 = QtGui.QLabel(self.gbInput)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(150, 0))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_3.addWidget(self.label_4)
        self.leMergeMapping = QgsFileDropEdit(self.gbInput)
        self.leMergeMapping.setObjectName(_fromUtf8("leMergeMapping"))
        self.horizontalLayout_3.addWidget(self.leMergeMapping)
        self.bBrowseMergeMapping = QtGui.QToolButton(self.gbInput)
        self.bBrowseMergeMapping.setObjectName(_fromUtf8("bBrowseMergeMapping"))
        self.horizontalLayout_3.addWidget(self.bBrowseMergeMapping)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_5 = QtGui.QLabel(self.gbInput)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(150, 0))
        self.label_5.setBaseSize(QtCore.QSize(150, 0))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_5.addWidget(self.label_5)
        self.cbDemLayer = QtGui.QComboBox(self.gbInput)
        self.cbDemLayer.setObjectName(_fromUtf8("cbDemLayer"))
        self.horizontalLayout_5.addWidget(self.cbDemLayer)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.gbOutput = QtGui.QGroupBox(ToporobotImporter)
        self.gbOutput.setGeometry(QtCore.QRect(10, 190, 561, 311))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gbOutput.sizePolicy().hasHeightForWidth())
        self.gbOutput.setSizePolicy(sizePolicy)
        self.gbOutput.setObjectName(_fromUtf8("gbOutput"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.gbOutput)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_9 = QtGui.QLabel(self.gbOutput)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_2.addWidget(self.label_9)
        self._2 = QtGui.QHBoxLayout()
        self._2.setObjectName(_fromUtf8("_2"))
        self.label_16 = QtGui.QLabel(self.gbOutput)
        self.label_16.setText(_fromUtf8(""))
        self.label_16.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/toporobotimporter/images/schema_points.png")))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self._2.addWidget(self.label_16)
        self.lbOutPoints = QtGui.QLabel(self.gbOutput)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbOutPoints.sizePolicy().hasHeightForWidth())
        self.lbOutPoints.setSizePolicy(sizePolicy)
        self.lbOutPoints.setMinimumSize(QtCore.QSize(100, 0))
        self.lbOutPoints.setObjectName(_fromUtf8("lbOutPoints"))
        self._2.addWidget(self.lbOutPoints)
        self.leOutPoints = QgsFileDropEdit(self.gbOutput)
        self.leOutPoints.setObjectName(_fromUtf8("leOutPoints"))
        self._2.addWidget(self.leOutPoints)
        self.bBrowseOutPoints = QtGui.QToolButton(self.gbOutput)
        self.bBrowseOutPoints.setObjectName(_fromUtf8("bBrowseOutPoints"))
        self._2.addWidget(self.bBrowseOutPoints)
        self.verticalLayout_2.addLayout(self._2)
        self._3 = QtGui.QHBoxLayout()
        self._3.setObjectName(_fromUtf8("_3"))
        self.label_17 = QtGui.QLabel(self.gbOutput)
        self.label_17.setText(_fromUtf8(""))
        self.label_17.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/toporobotimporter/images/schema_lines.png")))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self._3.addWidget(self.label_17)
        self.lbOutAims = QtGui.QLabel(self.gbOutput)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbOutAims.sizePolicy().hasHeightForWidth())
        self.lbOutAims.setSizePolicy(sizePolicy)
        self.lbOutAims.setMinimumSize(QtCore.QSize(100, 0))
        self.lbOutAims.setObjectName(_fromUtf8("lbOutAims"))
        self._3.addWidget(self.lbOutAims)
        self.leOutAims = QgsFileDropEdit(self.gbOutput)
        self.leOutAims.setObjectName(_fromUtf8("leOutAims"))
        self._3.addWidget(self.leOutAims)
        self.bBrowseOutAims = QtGui.QToolButton(self.gbOutput)
        self.bBrowseOutAims.setObjectName(_fromUtf8("bBrowseOutAims"))
        self._3.addWidget(self.bBrowseOutAims)
        self.verticalLayout_2.addLayout(self._3)
        self._4 = QtGui.QHBoxLayout()
        self._4.setObjectName(_fromUtf8("_4"))
        self.label_15 = QtGui.QLabel(self.gbOutput)
        self.label_15.setText(_fromUtf8(""))
        self.label_15.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/toporobotimporter/images/schema_polygons.png")))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self._4.addWidget(self.label_15)
        self.lbOutAimsSurface = QtGui.QLabel(self.gbOutput)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbOutAimsSurface.sizePolicy().hasHeightForWidth())
        self.lbOutAimsSurface.setSizePolicy(sizePolicy)
        self.lbOutAimsSurface.setMinimumSize(QtCore.QSize(100, 0))
        self.lbOutAimsSurface.setObjectName(_fromUtf8("lbOutAimsSurface"))
        self._4.addWidget(self.lbOutAimsSurface)
        self.leOutAimsSurface = QgsFileDropEdit(self.gbOutput)
        self.leOutAimsSurface.setObjectName(_fromUtf8("leOutAimsSurface"))
        self._4.addWidget(self.leOutAimsSurface)
        self.bBrowseOutAimsSurface = QtGui.QToolButton(self.gbOutput)
        self.bBrowseOutAimsSurface.setObjectName(_fromUtf8("bBrowseOutAimsSurface"))
        self._4.addWidget(self.bBrowseOutAimsSurface)
        self.verticalLayout_2.addLayout(self._4)
        self._5 = QtGui.QHBoxLayout()
        self._5.setObjectName(_fromUtf8("_5"))
        self.label_13 = QtGui.QLabel(self.gbOutput)
        self.label_13.setText(_fromUtf8(""))
        self.label_13.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/toporobotimporter/images/schema_line.png")))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self._5.addWidget(self.label_13)
        self.lbOutSeries = QtGui.QLabel(self.gbOutput)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbOutSeries.sizePolicy().hasHeightForWidth())
        self.lbOutSeries.setSizePolicy(sizePolicy)
        self.lbOutSeries.setMinimumSize(QtCore.QSize(100, 0))
        self.lbOutSeries.setObjectName(_fromUtf8("lbOutSeries"))
        self._5.addWidget(self.lbOutSeries)
        self.leOutSeries = QgsFileDropEdit(self.gbOutput)
        self.leOutSeries.setEnabled(True)
        self.leOutSeries.setObjectName(_fromUtf8("leOutSeries"))
        self._5.addWidget(self.leOutSeries)
        self.bBrowseOutSeries = QtGui.QToolButton(self.gbOutput)
        self.bBrowseOutSeries.setObjectName(_fromUtf8("bBrowseOutSeries"))
        self._5.addWidget(self.bBrowseOutSeries)
        self.verticalLayout_2.addLayout(self._5)
        self._6 = QtGui.QHBoxLayout()
        self._6.setObjectName(_fromUtf8("_6"))
        self.label_14 = QtGui.QLabel(self.gbOutput)
        self.label_14.setText(_fromUtf8(""))
        self.label_14.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/toporobotimporter/images/schema_polygon.png")))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self._6.addWidget(self.label_14)
        self.lbOutSeriesBorder = QtGui.QLabel(self.gbOutput)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbOutSeriesBorder.sizePolicy().hasHeightForWidth())
        self.lbOutSeriesBorder.setSizePolicy(sizePolicy)
        self.lbOutSeriesBorder.setMinimumSize(QtCore.QSize(100, 0))
        self.lbOutSeriesBorder.setObjectName(_fromUtf8("lbOutSeriesBorder"))
        self._6.addWidget(self.lbOutSeriesBorder)
        self.leOutSeriesBorder = QgsFileDropEdit(self.gbOutput)
        self.leOutSeriesBorder.setEnabled(True)
        self.leOutSeriesBorder.setObjectName(_fromUtf8("leOutSeriesBorder"))
        self._6.addWidget(self.leOutSeriesBorder)
        self.bBrowseOutSeriesBorder = QtGui.QToolButton(self.gbOutput)
        self.bBrowseOutSeriesBorder.setObjectName(_fromUtf8("bBrowseOutSeriesBorder"))
        self._6.addWidget(self.bBrowseOutSeriesBorder)
        self.verticalLayout_2.addLayout(self._6)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_6 = QtGui.QLabel(self.gbOutput)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_4.addWidget(self.label_6)
        self.leSRS = QtGui.QLineEdit(self.gbOutput)
        self.leSRS.setObjectName(_fromUtf8("leSRS"))
        self.horizontalLayout_4.addWidget(self.leSRS)
        self.bSRS = QtGui.QToolButton(self.gbOutput)
        self.bSRS.setObjectName(_fromUtf8("bSRS"))
        self.horizontalLayout_4.addWidget(self.bSRS)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_3 = QtGui.QLabel(self.gbOutput)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_6.addWidget(self.label_3)
        self.rbOverride = QtGui.QRadioButton(self.gbOutput)
        self.rbOverride.setChecked(True)
        self.rbOverride.setObjectName(_fromUtf8("rbOverride"))
        self.horizontalLayout_6.addWidget(self.rbOverride)
        self.rbAppend = QtGui.QRadioButton(self.gbOutput)
        self.rbAppend.setObjectName(_fromUtf8("rbAppend"))
        self.horizontalLayout_6.addWidget(self.rbAppend)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.cbDisplayInQgis = QtGui.QCheckBox(self.gbOutput)
        self.cbDisplayInQgis.setChecked(True)
        self.cbDisplayInQgis.setObjectName(_fromUtf8("cbDisplayInQgis"))
        self.verticalLayout_2.addWidget(self.cbDisplayInQgis)

        self.retranslateUi(ToporobotImporter)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), ToporobotImporter.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), ToporobotImporter.reject)
        QtCore.QMetaObject.connectSlotsByName(ToporobotImporter)

    def retranslateUi(self, ToporobotImporter):
        ToporobotImporter.setWindowTitle(_translate("ToporobotImporter", "ToporobotImporter", None))
        self.gbInput.setTitle(_translate("ToporobotImporter", "Input data", None))
        self.label.setText(_translate("ToporobotImporter", "Toporobot .Text file", None))
        self.bBrowseToporobotText.setText(_translate("ToporobotImporter", "Browse", None))
        self.label_2.setText(_translate("ToporobotImporter", "Toporobot .Coord file", None))
        self.bBrowseToporobotCoord.setText(_translate("ToporobotImporter", "Browse", None))
        self.label_4.setText(_translate("ToporobotImporter", "Merge\'s mapping file (optional)", None))
        self.bBrowseMergeMapping.setText(_translate("ToporobotImporter", "Browse", None))
        self.label_5.setText(_translate("ToporobotImporter", "Layer with Elevation (optional)", None))
        self.gbOutput.setTitle(_translate("ToporobotImporter", "Output shapefiles", None))
        self.label_9.setText(_translate("ToporobotImporter", "Define the shapefile(s) you want to export (and let the others empty)", None))
        self.lbOutPoints.setText(_translate("ToporobotImporter", "Stations as point", None))
        self.bBrowseOutPoints.setText(_translate("ToporobotImporter", "Browse", None))
        self.lbOutAims.setText(_translate("ToporobotImporter", "Stations as line", None))
        self.bBrowseOutAims.setText(_translate("ToporobotImporter", "Browse", None))
        self.lbOutAimsSurface.setText(_translate("ToporobotImporter", "Stations as surface", None))
        self.bBrowseOutAimsSurface.setText(_translate("ToporobotImporter", "Browse", None))
        self.lbOutSeries.setText(_translate("ToporobotImporter", "Series as lines", None))
        self.bBrowseOutSeries.setText(_translate("ToporobotImporter", "Browse", None))
        self.lbOutSeriesBorder.setText(_translate("ToporobotImporter", "Series as surfaces", None))
        self.bBrowseOutSeriesBorder.setText(_translate("ToporobotImporter", "Browse", None))
        self.label_6.setText(_translate("ToporobotImporter", "Coordinate reference system (optional)", None))
        self.bSRS.setText(_translate("ToporobotImporter", "...", None))
        self.label_3.setText(_translate("ToporobotImporter", "Output by", None))
        self.rbOverride.setText(_translate("ToporobotImporter", "Overriding", None))
        self.rbAppend.setText(_translate("ToporobotImporter", "Appending", None))
        self.cbDisplayInQgis.setText(_translate("ToporobotImporter", "Show the created layer(s) in QGIS", None))

from qgis.gui import QgsFileDropEdit
